if (!window.PDoc) window.PDoc = {};
PDoc.elements = {
  'Language section': { 'name': 'Language section', 'type': 'section', 'path': '../language_section.html' },
'Try': { 'name': 'Try', 'type': 'namespace', 'path': '../language/try.html' },
'Try.these': { 'name': 'Try.these', 'type': 'class method', 'path': '../language/try.html#these-class_method' },
'Class': { 'name': 'Class', 'type': 'namespace', 'path': '../language/class.html' },
'Class.create': { 'name': 'Class.create', 'type': 'class method', 'path': '../language/class.html#create-class_method' },
'Class#addMethods': { 'name': 'Class#addMethods', 'type': 'instance method', 'path': '../language/class.html#addmethods-instance_method' },
'Object': { 'name': 'Object', 'type': 'class', 'path': '../language/object.html' },
'Object.extend': { 'name': 'Object.extend', 'type': 'class method', 'path': '../language/object.html#extend-class_method' },
'Object.inspect': { 'name': 'Object.inspect', 'type': 'class method', 'path': '../language/object.html#inspect-class_method' },
'Object.toJSON': { 'name': 'Object.toJSON', 'type': 'class method', 'path': '../language/object.html#tojson-class_method' },
'Object.toQueryString': { 'name': 'Object.toQueryString', 'type': 'class method', 'path': '../language/object.html#toquerystring-class_method' },
'Object.toHTML': { 'name': 'Object.toHTML', 'type': 'class method', 'path': '../language/object.html#tohtml-class_method' },
'Object.keys': { 'name': 'Object.keys', 'type': 'class method', 'path': '../language/object.html#keys-class_method' },
'Object.values': { 'name': 'Object.values', 'type': 'class method', 'path': '../language/object.html#values-class_method' },
'Object.clone': { 'name': 'Object.clone', 'type': 'class method', 'path': '../language/object.html#clone-class_method' },
'Object.isElement': { 'name': 'Object.isElement', 'type': 'class method', 'path': '../language/object.html#iselement-class_method' },
'Object.isArray': { 'name': 'Object.isArray', 'type': 'class method', 'path': '../language/object.html#isarray-class_method' },
'Object.isHash': { 'name': 'Object.isHash', 'type': 'class method', 'path': '../language/object.html#ishash-class_method' },
'Object.isFunction': { 'name': 'Object.isFunction', 'type': 'class method', 'path': '../language/object.html#isfunction-class_method' },
'Object.isString': { 'name': 'Object.isString', 'type': 'class method', 'path': '../language/object.html#isstring-class_method' },
'Object.isNumber': { 'name': 'Object.isNumber', 'type': 'class method', 'path': '../language/object.html#isnumber-class_method' },
'Object.isUndefined': { 'name': 'Object.isUndefined', 'type': 'class method', 'path': '../language/object.html#isundefined-class_method' },
'Function': { 'name': 'Function', 'type': 'class', 'path': '../language/function.html' },
'Function#argumentNames': { 'name': 'Function#argumentNames', 'type': 'instance method', 'path': '../language/function.html#argumentnames-instance_method' },
'Function#bind': { 'name': 'Function#bind', 'type': 'instance method', 'path': '../language/function.html#bind-instance_method' },
'Function#bindAsEventListener': { 'name': 'Function#bindAsEventListener', 'type': 'instance method', 'path': '../language/function.html#bindaseventlistener-instance_method' },
'Function#curry': { 'name': 'Function#curry', 'type': 'instance method', 'path': '../language/function.html#curry-instance_method' },
'Function#delay': { 'name': 'Function#delay', 'type': 'instance method', 'path': '../language/function.html#delay-instance_method' },
'Function#defer': { 'name': 'Function#defer', 'type': 'instance method', 'path': '../language/function.html#defer-instance_method' },
'Function#wrap': { 'name': 'Function#wrap', 'type': 'instance method', 'path': '../language/function.html#wrap-instance_method' },
'Function#methodize': { 'name': 'Function#methodize', 'type': 'instance method', 'path': '../language/function.html#methodize-instance_method' },
'Date': { 'name': 'Date', 'type': 'class', 'path': '../language/date.html' },
'Date#toJSON': { 'name': 'Date#toJSON', 'type': 'instance method', 'path': '../language/date.html#tojson-instance_method' },
'RegExp': { 'name': 'RegExp', 'type': 'class', 'path': '../language/regexp.html' },
'RegExp#match': { 'name': 'RegExp#match', 'type': 'instance method', 'path': '../language/regexp.html#match-instance_method' },
'RegExp.escape': { 'name': 'RegExp.escape', 'type': 'class method', 'path': '../language/regexp.html#escape-class_method' },
'PeriodicalExecuter': { 'name': 'PeriodicalExecuter', 'type': 'class', 'path': '../language/periodicalexecuter.html' },
'new PeriodicalExecuter': { 'name': 'new PeriodicalExecuter', 'type': 'constructor', 'path': '../language/periodicalexecuter.html#new-constructor' },
'PeriodicalExecuter#stop': { 'name': 'PeriodicalExecuter#stop', 'type': 'instance method', 'path': '../language/periodicalexecuter.html#stop-instance_method' },
'String': { 'name': 'String', 'type': 'class', 'path': '../language/string.html' },
'String.interpret': { 'name': 'String.interpret', 'type': 'class method', 'path': '../language/string.html#interpret-class_method' },
'String#gsub': { 'name': 'String#gsub', 'type': 'instance method', 'path': '../language/string.html#gsub-instance_method' },
'String#sub': { 'name': 'String#sub', 'type': 'instance method', 'path': '../language/string.html#sub-instance_method' },
'String#scan': { 'name': 'String#scan', 'type': 'instance method', 'path': '../language/string.html#scan-instance_method' },
'String#truncate': { 'name': 'String#truncate', 'type': 'instance method', 'path': '../language/string.html#truncate-instance_method' },
'String#strip': { 'name': 'String#strip', 'type': 'instance method', 'path': '../language/string.html#strip-instance_method' },
'String#stripTags': { 'name': 'String#stripTags', 'type': 'instance method', 'path': '../language/string.html#striptags-instance_method' },
'String#stripScripts': { 'name': 'String#stripScripts', 'type': 'instance method', 'path': '../language/string.html#stripscripts-instance_method' },
'String#extractScripts': { 'name': 'String#extractScripts', 'type': 'instance method', 'path': '../language/string.html#extractscripts-instance_method' },
'String#evalScripts': { 'name': 'String#evalScripts', 'type': 'instance method', 'path': '../language/string.html#evalscripts-instance_method' },
'String#escapeHTML': { 'name': 'String#escapeHTML', 'type': 'instance method', 'path': '../language/string.html#escapehtml-instance_method' },
'String#unescapeHTML': { 'name': 'String#unescapeHTML', 'type': 'instance method', 'path': '../language/string.html#unescapehtml-instance_method' },
'String#parseQuery': { 'name': 'String#parseQuery', 'type': 'instance method', 'path': '../language/string.html#parsequery-instance_method' },
'String#toQueryParams': { 'name': 'String#toQueryParams', 'type': 'instance method', 'path': '../language/string.html#toqueryparams-instance_method' },
'String#toArray': { 'name': 'String#toArray', 'type': 'instance method', 'path': '../language/string.html#toarray-instance_method' },
'String#succ': { 'name': 'String#succ', 'type': 'instance method', 'path': '../language/string.html#succ-instance_method' },
'String#times': { 'name': 'String#times', 'type': 'instance method', 'path': '../language/string.html#times-instance_method' },
'String#camelize': { 'name': 'String#camelize', 'type': 'instance method', 'path': '../language/string.html#camelize-instance_method' },
'String#capitalize': { 'name': 'String#capitalize', 'type': 'instance method', 'path': '../language/string.html#capitalize-instance_method' },
'String#underscore': { 'name': 'String#underscore', 'type': 'instance method', 'path': '../language/string.html#underscore-instance_method' },
'String#dasherize': { 'name': 'String#dasherize', 'type': 'instance method', 'path': '../language/string.html#dasherize-instance_method' },
'String#inspect': { 'name': 'String#inspect', 'type': 'instance method', 'path': '../language/string.html#inspect-instance_method' },
'String#toJSON': { 'name': 'String#toJSON', 'type': 'instance method', 'path': '../language/string.html#tojson-instance_method' },
'String#unfilterJSON': { 'name': 'String#unfilterJSON', 'type': 'instance method', 'path': '../language/string.html#unfilterjson-instance_method' },
'String#isJSON': { 'name': 'String#isJSON', 'type': 'instance method', 'path': '../language/string.html#isjson-instance_method' },
'String#evalJSON': { 'name': 'String#evalJSON', 'type': 'instance method', 'path': '../language/string.html#evaljson-instance_method' },
'String#include': { 'name': 'String#include', 'type': 'instance method', 'path': '../language/string.html#include-instance_method' },
'String#startsWith': { 'name': 'String#startsWith', 'type': 'instance method', 'path': '../language/string.html#startswith-instance_method' },
'String#endsWith': { 'name': 'String#endsWith', 'type': 'instance method', 'path': '../language/string.html#endswith-instance_method' },
'String#empty': { 'name': 'String#empty', 'type': 'instance method', 'path': '../language/string.html#empty-instance_method' },
'String#blank': { 'name': 'String#blank', 'type': 'instance method', 'path': '../language/string.html#blank-instance_method' },
'String#interpolate': { 'name': 'String#interpolate', 'type': 'instance method', 'path': '../language/string.html#interpolate-instance_method' },
'Template': { 'name': 'Template', 'type': 'class', 'path': '../language/template.html' },
'new Template': { 'name': 'new Template', 'type': 'constructor', 'path': '../language/template.html#new-constructor' },
'Template#evaluate': { 'name': 'Template#evaluate', 'type': 'instance method', 'path': '../language/template.html#evaluate-instance_method' },
'Enumerable': { 'name': 'Enumerable', 'type': 'mixin', 'path': '../language/enumerable.html' },
'Enumerable#each': { 'name': 'Enumerable#each', 'type': 'instance method', 'path': '../language/enumerable.html#each-instance_method' },
'Enumerable#eachSlice': { 'name': 'Enumerable#eachSlice', 'type': 'instance method', 'path': '../language/enumerable.html#eachslice-instance_method' },
'Enumerable#all': { 'name': 'Enumerable#all', 'type': 'instance method', 'path': '../language/enumerable.html#all-instance_method' },
'Enumerable#any': { 'name': 'Enumerable#any', 'type': 'instance method', 'path': '../language/enumerable.html#any-instance_method' },
'Enumerable#collect': { 'name': 'Enumerable#collect', 'type': 'instance method', 'path': '../language/enumerable.html#collect-instance_method' },
'Enumerable#detect': { 'name': 'Enumerable#detect', 'type': 'instance method', 'path': '../language/enumerable.html#detect-instance_method' },
'Enumerable#findAll': { 'name': 'Enumerable#findAll', 'type': 'instance method', 'path': '../language/enumerable.html#findall-instance_method' },
'Enumerable#grep': { 'name': 'Enumerable#grep', 'type': 'instance method', 'path': '../language/enumerable.html#grep-instance_method' },
'Enumerable#include': { 'name': 'Enumerable#include', 'type': 'instance method', 'path': '../language/enumerable.html#include-instance_method' },
'Enumerable#inGroupsOf': { 'name': 'Enumerable#inGroupsOf', 'type': 'instance method', 'path': '../language/enumerable.html#ingroupsof-instance_method' },
'Enumerable#inject': { 'name': 'Enumerable#inject', 'type': 'instance method', 'path': '../language/enumerable.html#inject-instance_method' },
'Enumerable#invoke': { 'name': 'Enumerable#invoke', 'type': 'instance method', 'path': '../language/enumerable.html#invoke-instance_method' },
'Enumerable#max': { 'name': 'Enumerable#max', 'type': 'instance method', 'path': '../language/enumerable.html#max-instance_method' },
'Enumerable#min': { 'name': 'Enumerable#min', 'type': 'instance method', 'path': '../language/enumerable.html#min-instance_method' },
'Enumerable#partition': { 'name': 'Enumerable#partition', 'type': 'instance method', 'path': '../language/enumerable.html#partition-instance_method' },
'Enumerable#pluck': { 'name': 'Enumerable#pluck', 'type': 'instance method', 'path': '../language/enumerable.html#pluck-instance_method' },
'Enumerable#reject': { 'name': 'Enumerable#reject', 'type': 'instance method', 'path': '../language/enumerable.html#reject-instance_method' },
'Enumerable#sortBy': { 'name': 'Enumerable#sortBy', 'type': 'instance method', 'path': '../language/enumerable.html#sortby-instance_method' },
'Enumerable#toArray': { 'name': 'Enumerable#toArray', 'type': 'instance method', 'path': '../language/enumerable.html#toarray-instance_method' },
'Enumerable#zip': { 'name': 'Enumerable#zip', 'type': 'instance method', 'path': '../language/enumerable.html#zip-instance_method' },
'Enumerable#size': { 'name': 'Enumerable#size', 'type': 'instance method', 'path': '../language/enumerable.html#size-instance_method' },
'Enumerable#inspect': { 'name': 'Enumerable#inspect', 'type': 'instance method', 'path': '../language/enumerable.html#inspect-instance_method' },
'Enumerable#map': { 'name': 'Enumerable#map', 'type': 'instance method', 'path': '../language/enumerable.html#map-instance_method' },
'Enumerable#some': { 'name': 'Enumerable#some', 'type': 'instance method', 'path': '../language/enumerable.html#some-instance_method' },
'Enumerable#every': { 'name': 'Enumerable#every', 'type': 'instance method', 'path': '../language/enumerable.html#every-instance_method' },
'Enumerable#select': { 'name': 'Enumerable#select', 'type': 'instance method', 'path': '../language/enumerable.html#select-instance_method' },
'Enumerable#filter': { 'name': 'Enumerable#filter', 'type': 'instance method', 'path': '../language/enumerable.html#filter-instance_method' },
'Enumerable#member': { 'name': 'Enumerable#member', 'type': 'instance method', 'path': '../language/enumerable.html#member-instance_method' },
'Enumerable#entries': { 'name': 'Enumerable#entries', 'type': 'instance method', 'path': '../language/enumerable.html#entries-instance_method' },
'Enumerable#find': { 'name': 'Enumerable#find', 'type': 'instance method', 'path': '../language/enumerable.html#find-instance_method' },
'$A': { 'name': '$A', 'type': 'utility', 'path': '../language/dollara.html' },
'$w': { 'name': '$w', 'type': 'utility', 'path': '../language/dollarw.html' },
'Array.from': { 'name': 'Array.from', 'type': 'class method', 'path': '../language/array.html#from-class_method' },
'Array': { 'name': 'Array', 'type': 'class', 'path': '../language/array.html' },
'Array#clear': { 'name': 'Array#clear', 'type': 'instance method', 'path': '../language/array.html#clear-instance_method' },
'Array#first': { 'name': 'Array#first', 'type': 'instance method', 'path': '../language/array.html#first-instance_method' },
'Array#last': { 'name': 'Array#last', 'type': 'instance method', 'path': '../language/array.html#last-instance_method' },
'Array#compact': { 'name': 'Array#compact', 'type': 'instance method', 'path': '../language/array.html#compact-instance_method' },
'Array#flatten': { 'name': 'Array#flatten', 'type': 'instance method', 'path': '../language/array.html#flatten-instance_method' },
'Array#without': { 'name': 'Array#without', 'type': 'instance method', 'path': '../language/array.html#without-instance_method' },
'Array#reverse': { 'name': 'Array#reverse', 'type': 'instance method', 'path': '../language/array.html#reverse-instance_method' },
'Array#uniq': { 'name': 'Array#uniq', 'type': 'instance method', 'path': '../language/array.html#uniq-instance_method' },
'Array#intersect': { 'name': 'Array#intersect', 'type': 'instance method', 'path': '../language/array.html#intersect-instance_method' },
'Array#toArray': { 'name': 'Array#toArray', 'type': 'instance method', 'path': '../language/array.html#toarray-instance_method' },
'Array#clone': { 'name': 'Array#clone', 'type': 'instance method', 'path': '../language/array.html#clone-instance_method' },
'Array#size': { 'name': 'Array#size', 'type': 'instance method', 'path': '../language/array.html#size-instance_method' },
'Array#inspect': { 'name': 'Array#inspect', 'type': 'instance method', 'path': '../language/array.html#inspect-instance_method' },
'Array#toJSON': { 'name': 'Array#toJSON', 'type': 'instance method', 'path': '../language/array.html#tojson-instance_method' },
'Array#indexOf': { 'name': 'Array#indexOf', 'type': 'instance method', 'path': '../language/array.html#indexof-instance_method' },
'Array#lastIndexOf': { 'name': 'Array#lastIndexOf', 'type': 'instance method', 'path': '../language/array.html#lastindexof-instance_method' },
'$H': { 'name': '$H', 'type': 'utility', 'path': '../language/dollarh.html' },
'Hash': { 'name': 'Hash', 'type': 'class', 'path': '../language/hash.html' },
'new Hash': { 'name': 'new Hash', 'type': 'constructor', 'path': '../language/hash.html#new-constructor' },
'Hash#set': { 'name': 'Hash#set', 'type': 'instance method', 'path': '../language/hash.html#set-instance_method' },
'Hash#get': { 'name': 'Hash#get', 'type': 'instance method', 'path': '../language/hash.html#get-instance_method' },
'Hash#unset': { 'name': 'Hash#unset', 'type': 'instance method', 'path': '../language/hash.html#unset-instance_method' },
'Hash#toObject': { 'name': 'Hash#toObject', 'type': 'instance method', 'path': '../language/hash.html#toobject-instance_method' },
'Hash#keys': { 'name': 'Hash#keys', 'type': 'instance method', 'path': '../language/hash.html#keys-instance_method' },
'Hash#values': { 'name': 'Hash#values', 'type': 'instance method', 'path': '../language/hash.html#values-instance_method' },
'Hash#index': { 'name': 'Hash#index', 'type': 'instance method', 'path': '../language/hash.html#index-instance_method' },
'Hash#merge': { 'name': 'Hash#merge', 'type': 'instance method', 'path': '../language/hash.html#merge-instance_method' },
'Hash#update': { 'name': 'Hash#update', 'type': 'instance method', 'path': '../language/hash.html#update-instance_method' },
'Hash#toQueryString': { 'name': 'Hash#toQueryString', 'type': 'instance method', 'path': '../language/hash.html#toquerystring-instance_method' },
'Hash#inspect': { 'name': 'Hash#inspect', 'type': 'instance method', 'path': '../language/hash.html#inspect-instance_method' },
'Hash#toJSON': { 'name': 'Hash#toJSON', 'type': 'instance method', 'path': '../language/hash.html#tojson-instance_method' },
'Hash#clone': { 'name': 'Hash#clone', 'type': 'instance method', 'path': '../language/hash.html#clone-instance_method' },
'Number': { 'name': 'Number', 'type': 'class', 'path': '../language/number.html' },
'Number#toColorPart': { 'name': 'Number#toColorPart', 'type': 'instance method', 'path': '../language/number.html#tocolorpart-instance_method' },
'Number#succ': { 'name': 'Number#succ', 'type': 'instance method', 'path': '../language/number.html#succ-instance_method' },
'Number#times': { 'name': 'Number#times', 'type': 'instance method', 'path': '../language/number.html#times-instance_method' },
'Number#toPaddedString': { 'name': 'Number#toPaddedString', 'type': 'instance method', 'path': '../language/number.html#topaddedstring-instance_method' },
'Number#toJSON': { 'name': 'Number#toJSON', 'type': 'instance method', 'path': '../language/number.html#tojson-instance_method' },
'Number#abs': { 'name': 'Number#abs', 'type': 'instance method', 'path': '../language/number.html#abs-instance_method' },
'Number#round': { 'name': 'Number#round', 'type': 'instance method', 'path': '../language/number.html#round-instance_method' },
'Number#ceil': { 'name': 'Number#ceil', 'type': 'instance method', 'path': '../language/number.html#ceil-instance_method' },
'Number#floor': { 'name': 'Number#floor', 'type': 'instance method', 'path': '../language/number.html#floor-instance_method' },
'ObjectRange': { 'name': 'ObjectRange', 'type': 'class', 'path': '../language/objectrange.html' },
'$R': { 'name': '$R', 'type': 'utility', 'path': '../language/dollarr.html' },
'new ObjectRange': { 'name': 'new ObjectRange', 'type': 'constructor', 'path': '../language/objectrange.html#new-constructor' },
'ObjectRange#include': { 'name': 'ObjectRange#include', 'type': 'instance method', 'path': '../language/objectrange.html#include-instance_method' },
'Ajax section': { 'name': 'Ajax section', 'type': 'section', 'path': '../ajax_section.html' },
'Ajax': { 'name': 'Ajax', 'type': 'namespace', 'path': '../ajax/ajax.html' },
'Ajax.activeRequestCount': { 'name': 'Ajax.activeRequestCount', 'type': 'class property', 'path': '../ajax/ajax.html#activerequestcount-class_property' },
'Ajax.Responders': { 'name': 'Ajax.Responders', 'type': 'namespace', 'path': '../ajax/ajax/responders.html' },
'Ajax.Responders.register': { 'name': 'Ajax.Responders.register', 'type': 'class method', 'path': '../ajax/ajax/responders.html#register-class_method' },
'Ajax.Responders.unregister': { 'name': 'Ajax.Responders.unregister', 'type': 'class method', 'path': '../ajax/ajax/responders.html#unregister-class_method' },
'Ajax.Request': { 'name': 'Ajax.Request', 'type': 'class', 'path': '../ajax/ajax/request.html' },
'new Ajax.Request': { 'name': 'new Ajax.Request', 'type': 'constructor', 'path': '../ajax/ajax/request.html#new-constructor' },
'Ajax.Request#success': { 'name': 'Ajax.Request#success', 'type': 'instance method', 'path': '../ajax/ajax/request.html#success-instance_method' },
'Ajax.Request#getHeader': { 'name': 'Ajax.Request#getHeader', 'type': 'instance method', 'path': '../ajax/ajax/request.html#getheader-instance_method' },
'Ajax.Response': { 'name': 'Ajax.Response', 'type': 'class', 'path': '../ajax/ajax/response.html' },
'Ajax.Response#readyState': { 'name': 'Ajax.Response#readyState', 'type': 'instance property', 'path': '../ajax/ajax/response.html#readystate-instance_property' },
'Ajax.Response#responseText': { 'name': 'Ajax.Response#responseText', 'type': 'instance property', 'path': '../ajax/ajax/response.html#responsetext-instance_property' },
'Ajax.Response#responseXML': { 'name': 'Ajax.Response#responseXML', 'type': 'instance property', 'path': '../ajax/ajax/response.html#responsexml-instance_property' },
'Ajax.Response#responseJSON': { 'name': 'Ajax.Response#responseJSON', 'type': 'instance property', 'path': '../ajax/ajax/response.html#responsejson-instance_property' },
'Ajax.Response#headerJSON': { 'name': 'Ajax.Response#headerJSON', 'type': 'instance property', 'path': '../ajax/ajax/response.html#headerjson-instance_property' },
'Ajax.Response#request': { 'name': 'Ajax.Response#request', 'type': 'instance property', 'path': '../ajax/ajax/response.html#request-instance_property' },
'Ajax.Response#transport': { 'name': 'Ajax.Response#transport', 'type': 'instance property', 'path': '../ajax/ajax/response.html#transport-instance_property' },
'Ajax.Response#status': { 'name': 'Ajax.Response#status', 'type': 'instance property', 'path': '../ajax/ajax/response.html#status-instance_property' },
'Ajax.Response#statusText': { 'name': 'Ajax.Response#statusText', 'type': 'instance property', 'path': '../ajax/ajax/response.html#statustext-instance_property' },
'Ajax.Response#getHeader': { 'name': 'Ajax.Response#getHeader', 'type': 'instance method', 'path': '../ajax/ajax/response.html#getheader-instance_method' },
'Ajax.Response#getAllHeaders': { 'name': 'Ajax.Response#getAllHeaders', 'type': 'instance method', 'path': '../ajax/ajax/response.html#getallheaders-instance_method' },
'Ajax.Response.getResponseHeader': { 'name': 'Ajax.Response.getResponseHeader', 'type': 'class method', 'path': '../ajax/ajax/response.html#getresponseheader-class_method' },
'Ajax.Response.getAllResponseHeaders': { 'name': 'Ajax.Response.getAllResponseHeaders', 'type': 'class method', 'path': '../ajax/ajax/response.html#getallresponseheaders-class_method' },
'Ajax.Updater': { 'name': 'Ajax.Updater', 'type': 'class', 'path': '../ajax/ajax/updater.html' },
'new Ajax.Updater': { 'name': 'new Ajax.Updater', 'type': 'constructor', 'path': '../ajax/ajax/updater.html#new-constructor' },
'Ajax.PeriodicalUpdater': { 'name': 'Ajax.PeriodicalUpdater', 'type': 'class', 'path': '../ajax/ajax/periodicalupdater.html' },
'new Ajax.PeriodicalUpdater': { 'name': 'new Ajax.PeriodicalUpdater', 'type': 'constructor', 'path': '../ajax/ajax/periodicalupdater.html#new-constructor' },
'Ajax.PeriodicalUpdater#start': { 'name': 'Ajax.PeriodicalUpdater#start', 'type': 'instance method', 'path': '../ajax/ajax/periodicalupdater.html#start-instance_method' },
'Ajax.PeriodicalUpdater#stop': { 'name': 'Ajax.PeriodicalUpdater#stop', 'type': 'instance method', 'path': '../ajax/ajax/periodicalupdater.html#stop-instance_method' },
'DOM section': { 'name': 'DOM section', 'type': 'section', 'path': '../dom_section.html' },
'$': { 'name': '$', 'type': 'utility', 'path': '../dom/dollar.html' },
'Element': { 'name': 'Element', 'type': 'class', 'path': '../dom/element.html' },
'new Element': { 'name': 'new Element', 'type': 'constructor', 'path': '../dom/element.html#new-constructor' },
'Element#visible': { 'name': 'Element#visible', 'type': 'instance method', 'path': '../dom/element.html#visible-instance_method' },
'Element#toggle': { 'name': 'Element#toggle', 'type': 'instance method', 'path': '../dom/element.html#toggle-instance_method' },
'Element#hide': { 'name': 'Element#hide', 'type': 'instance method', 'path': '../dom/element.html#hide-instance_method' },
'Element#show': { 'name': 'Element#show', 'type': 'instance method', 'path': '../dom/element.html#show-instance_method' },
'Element#remove': { 'name': 'Element#remove', 'type': 'instance method', 'path': '../dom/element.html#remove-instance_method' },
'Element#update': { 'name': 'Element#update', 'type': 'instance method', 'path': '../dom/element.html#update-instance_method' },
'Element#replace': { 'name': 'Element#replace', 'type': 'instance method', 'path': '../dom/element.html#replace-instance_method' },
'Element#insert': { 'name': 'Element#insert', 'type': 'instance method', 'path': '../dom/element.html#insert-instance_method' },
'Element#wrap': { 'name': 'Element#wrap', 'type': 'instance method', 'path': '../dom/element.html#wrap-instance_method' },
'Element#inspect': { 'name': 'Element#inspect', 'type': 'instance method', 'path': '../dom/element.html#inspect-instance_method' },
'Element#recursivelyCollect': { 'name': 'Element#recursivelyCollect', 'type': 'instance method', 'path': '../dom/element.html#recursivelycollect-instance_method' },
'Element#ancestors': { 'name': 'Element#ancestors', 'type': 'instance method', 'path': '../dom/element.html#ancestors-instance_method' },
'Element#descendants': { 'name': 'Element#descendants', 'type': 'instance method', 'path': '../dom/element.html#descendants-instance_method' },
'Element#firstDescendant': { 'name': 'Element#firstDescendant', 'type': 'instance method', 'path': '../dom/element.html#firstdescendant-instance_method' },
'Element#childElements': { 'name': 'Element#childElements', 'type': 'instance method', 'path': '../dom/element.html#childelements-instance_method' },
'Element#previousSiblings': { 'name': 'Element#previousSiblings', 'type': 'instance method', 'path': '../dom/element.html#previoussiblings-instance_method' },
'Element#nextSiblings': { 'name': 'Element#nextSiblings', 'type': 'instance method', 'path': '../dom/element.html#nextsiblings-instance_method' },
'Element#siblings': { 'name': 'Element#siblings', 'type': 'instance method', 'path': '../dom/element.html#siblings-instance_method' },
'Element#match': { 'name': 'Element#match', 'type': 'instance method', 'path': '../dom/element.html#match-instance_method' },
'Element#up': { 'name': 'Element#up', 'type': 'instance method', 'path': '../dom/element.html#up-instance_method' },
'Element#down': { 'name': 'Element#down', 'type': 'instance method', 'path': '../dom/element.html#down-instance_method' },
'Element#previous': { 'name': 'Element#previous', 'type': 'instance method', 'path': '../dom/element.html#previous-instance_method' },
'Element#next': { 'name': 'Element#next', 'type': 'instance method', 'path': '../dom/element.html#next-instance_method' },
'Element#select': { 'name': 'Element#select', 'type': 'instance method', 'path': '../dom/element.html#select-instance_method' },
'Element.adjacent': { 'name': 'Element.adjacent', 'type': 'class method', 'path': '../dom/element.html#adjacent-class_method' },
'Element#identify': { 'name': 'Element#identify', 'type': 'instance method', 'path': '../dom/element.html#identify-instance_method' },
'Element#readAttribute': { 'name': 'Element#readAttribute', 'type': 'instance method', 'path': '../dom/element.html#readattribute-instance_method' },
'Element#writeAttribute': { 'name': 'Element#writeAttribute', 'type': 'instance method', 'path': '../dom/element.html#writeattribute-instance_method' },
'Element#getHeight': { 'name': 'Element#getHeight', 'type': 'instance method', 'path': '../dom/element.html#getheight-instance_method' },
'Element#getWidth': { 'name': 'Element#getWidth', 'type': 'instance method', 'path': '../dom/element.html#getwidth-instance_method' },
'Element#classNames': { 'name': 'Element#classNames', 'type': 'instance method', 'path': '../dom/element.html#classnames-instance_method' },
'Element#hasClassName': { 'name': 'Element#hasClassName', 'type': 'instance method', 'path': '../dom/element.html#hasclassname-instance_method' },
'Element#addClassName': { 'name': 'Element#addClassName', 'type': 'instance method', 'path': '../dom/element.html#addclassname-instance_method' },
'Element#removeClassName': { 'name': 'Element#removeClassName', 'type': 'instance method', 'path': '../dom/element.html#removeclassname-instance_method' },
'Element#toggleClassName': { 'name': 'Element#toggleClassName', 'type': 'instance method', 'path': '../dom/element.html#toggleclassname-instance_method' },
'Element#cleanWhitespace': { 'name': 'Element#cleanWhitespace', 'type': 'instance method', 'path': '../dom/element.html#cleanwhitespace-instance_method' },
'Element#empty': { 'name': 'Element#empty', 'type': 'instance method', 'path': '../dom/element.html#empty-instance_method' },
'Element#descendantOf': { 'name': 'Element#descendantOf', 'type': 'instance method', 'path': '../dom/element.html#descendantof-instance_method' },
'Element#scrollTo': { 'name': 'Element#scrollTo', 'type': 'instance method', 'path': '../dom/element.html#scrollto-instance_method' },
'Element#getStyle': { 'name': 'Element#getStyle', 'type': 'instance method', 'path': '../dom/element.html#getstyle-instance_method' },
'Element#getOpacity': { 'name': 'Element#getOpacity', 'type': 'instance method', 'path': '../dom/element.html#getopacity-instance_method' },
'Element#setStyle': { 'name': 'Element#setStyle', 'type': 'instance method', 'path': '../dom/element.html#setstyle-instance_method' },
'Element#setOpacity': { 'name': 'Element#setOpacity', 'type': 'instance method', 'path': '../dom/element.html#setopacity-instance_method' },
'Element#getDimensions': { 'name': 'Element#getDimensions', 'type': 'instance method', 'path': '../dom/element.html#getdimensions-instance_method' },
'Element#makePositioned': { 'name': 'Element#makePositioned', 'type': 'instance method', 'path': '../dom/element.html#makepositioned-instance_method' },
'Element#undoPositioned': { 'name': 'Element#undoPositioned', 'type': 'instance method', 'path': '../dom/element.html#undopositioned-instance_method' },
'Element#makeClipping': { 'name': 'Element#makeClipping', 'type': 'instance method', 'path': '../dom/element.html#makeclipping-instance_method' },
'Element#undoClipping': { 'name': 'Element#undoClipping', 'type': 'instance method', 'path': '../dom/element.html#undoclipping-instance_method' },
'Element#cumulativeOffset': { 'name': 'Element#cumulativeOffset', 'type': 'instance method', 'path': '../dom/element.html#cumulativeoffset-instance_method' },
'Element#positionedOffset': { 'name': 'Element#positionedOffset', 'type': 'instance method', 'path': '../dom/element.html#positionedoffset-instance_method' },
'Element#absolutize': { 'name': 'Element#absolutize', 'type': 'instance method', 'path': '../dom/element.html#absolutize-instance_method' },
'Element#relativize': { 'name': 'Element#relativize', 'type': 'instance method', 'path': '../dom/element.html#relativize-instance_method' },
'Element.cumulativeScrollOffset': { 'name': 'Element.cumulativeScrollOffset', 'type': 'class method', 'path': '../dom/element.html#cumulativescrolloffset-class_method' },
'Element#getOffsetParent': { 'name': 'Element#getOffsetParent', 'type': 'instance method', 'path': '../dom/element.html#getoffsetparent-instance_method' },
'Element#viewportOffset': { 'name': 'Element#viewportOffset', 'type': 'instance method', 'path': '../dom/element.html#viewportoffset-instance_method' },
'Element#clonePosition': { 'name': 'Element#clonePosition', 'type': 'instance method', 'path': '../dom/element.html#cloneposition-instance_method' },
'Element#getElementsBySelector': { 'name': 'Element#getElementsBySelector', 'type': 'instance method', 'path': '../dom/element.html#getelementsbyselector-instance_method' },
'Element#childElements': { 'name': 'Element#childElements', 'type': 'instance method', 'path': '../dom/element.html#childelements-instance_method' },
'Element.extend': { 'name': 'Element.extend', 'type': 'class method', 'path': '../dom/element.html#extend-class_method' },
'Element.addMethods': { 'name': 'Element.addMethods', 'type': 'class method', 'path': '../dom/element.html#addmethods-class_method' },
'document.viewport': { 'name': 'document.viewport', 'type': 'namespace', 'path': '../dom/document/viewport.html' },
'document.viewport.getDimensions': { 'name': 'document.viewport.getDimensions', 'type': 'class method', 'path': '../dom/document/viewport.html#getdimensions-class_method' },
'document.viewport.getScrollOffsets': { 'name': 'document.viewport.getScrollOffsets', 'type': 'class method', 'path': '../dom/document/viewport.html#getscrolloffsets-class_method' },
'document.viewport.getWidth': { 'name': 'document.viewport.getWidth', 'type': 'class method', 'path': '../dom/document/viewport.html#getwidth-class_method' },
'document.viewport.getHeight': { 'name': 'document.viewport.getHeight', 'type': 'class method', 'path': '../dom/document/viewport.html#getheight-class_method' },
'Element#getStorage': { 'name': 'Element#getStorage', 'type': 'instance method', 'path': '../dom/element.html#getstorage-instance_method' },
'Element#store': { 'name': 'Element#store', 'type': 'instance method', 'path': '../dom/element.html#store-instance_method' },
'Element#retrieve': { 'name': 'Element#retrieve', 'type': 'instance method', 'path': '../dom/element.html#retrieve-instance_method' },
'Element#clone': { 'name': 'Element#clone', 'type': 'instance method', 'path': '../dom/element.html#clone-instance_method' },
'Selector': { 'name': 'Selector', 'type': 'class', 'path': '../dom/selector.html' },
'new Selector': { 'name': 'new Selector', 'type': 'constructor', 'path': '../dom/selector.html#new-constructor' },
'Selector#findElements': { 'name': 'Selector#findElements', 'type': 'instance method', 'path': '../dom/selector.html#findelements-instance_method' },
'Selector#match': { 'name': 'Selector#match', 'type': 'instance method', 'path': '../dom/selector.html#match-instance_method' },
'Selector.split': { 'name': 'Selector.split', 'type': 'class method', 'path': '../dom/selector.html#split-class_method' },
'Selector.matchElements': { 'name': 'Selector.matchElements', 'type': 'class method', 'path': '../dom/selector.html#matchelements-class_method' },
'Selector.findElement': { 'name': 'Selector.findElement', 'type': 'class method', 'path': '../dom/selector.html#findelement-class_method' },
'Selector.findChildElements': { 'name': 'Selector.findChildElements', 'type': 'class method', 'path': '../dom/selector.html#findchildelements-class_method' },
'$$': { 'name': '$$', 'type': 'utility', 'path': '../dom/dollardollar.html' },
'Form': { 'name': 'Form', 'type': 'namespace', 'path': '../dom/form.html' },
'Form.reset': { 'name': 'Form.reset', 'type': 'class method', 'path': '../dom/form.html#reset-class_method' },
'Form.serializeElements': { 'name': 'Form.serializeElements', 'type': 'class method', 'path': '../dom/form.html#serializeelements-class_method' },
'Form#serialize': { 'name': 'Form#serialize', 'type': 'instance method', 'path': '../dom/form.html#serialize-instance_method' },
'Form#getElements': { 'name': 'Form#getElements', 'type': 'instance method', 'path': '../dom/form.html#getelements-instance_method' },
'Form#getInputs': { 'name': 'Form#getInputs', 'type': 'instance method', 'path': '../dom/form.html#getinputs-instance_method' },
'Form#disable': { 'name': 'Form#disable', 'type': 'instance method', 'path': '../dom/form.html#disable-instance_method' },
'Form#enable': { 'name': 'Form#enable', 'type': 'instance method', 'path': '../dom/form.html#enable-instance_method' },
'Form#findFirstElement': { 'name': 'Form#findFirstElement', 'type': 'instance method', 'path': '../dom/form.html#findfirstelement-instance_method' },
'Form#focusFirstElement': { 'name': 'Form#focusFirstElement', 'type': 'instance method', 'path': '../dom/form.html#focusfirstelement-instance_method' },
'Form#request': { 'name': 'Form#request', 'type': 'instance method', 'path': '../dom/form.html#request-instance_method' },
'Form.Element': { 'name': 'Form.Element', 'type': 'namespace', 'path': '../dom/form/element.html' },
'Form.Element.focus': { 'name': 'Form.Element.focus', 'type': 'class method', 'path': '../dom/form/element.html#focus-class_method' },
'Form.Element.select': { 'name': 'Form.Element.select', 'type': 'class method', 'path': '../dom/form/element.html#select-class_method' },
'Form.Element#serialize': { 'name': 'Form.Element#serialize', 'type': 'instance method', 'path': '../dom/form/element.html#serialize-instance_method' },
'Form.Element#getValue': { 'name': 'Form.Element#getValue', 'type': 'instance method', 'path': '../dom/form/element.html#getvalue-instance_method' },
'Form.Element#setValue': { 'name': 'Form.Element#setValue', 'type': 'instance method', 'path': '../dom/form/element.html#setvalue-instance_method' },
'Form.Element#clear': { 'name': 'Form.Element#clear', 'type': 'instance method', 'path': '../dom/form/element.html#clear-instance_method' },
'Form.Element#present': { 'name': 'Form.Element#present', 'type': 'instance method', 'path': '../dom/form/element.html#present-instance_method' },
'Form.Element#activate': { 'name': 'Form.Element#activate', 'type': 'instance method', 'path': '../dom/form/element.html#activate-instance_method' },
'Form.Element#disable': { 'name': 'Form.Element#disable', 'type': 'instance method', 'path': '../dom/form/element.html#disable-instance_method' },
'Form.Element#enable': { 'name': 'Form.Element#enable', 'type': 'instance method', 'path': '../dom/form/element.html#enable-instance_method' },
'$F': { 'name': '$F', 'type': 'utility', 'path': '../dom/dollarf.html' },
'Abstract': { 'name': 'Abstract', 'type': 'namespace', 'path': '../dom/abstract.html' },
'Abstract.TimedObserver': { 'name': 'Abstract.TimedObserver', 'type': 'class', 'path': '../dom/abstract/timedobserver.html' },
'Form.Element.Observer': { 'name': 'Form.Element.Observer', 'type': 'class', 'path': '../dom/form/element/observer.html' },
'new Form.Element.Observer': { 'name': 'new Form.Element.Observer', 'type': 'constructor', 'path': '../dom/form/element/observer.html#new-constructor' },
'Form.Observer': { 'name': 'Form.Observer', 'type': 'class', 'path': '../dom/form/observer.html' },
'new Form.Observer': { 'name': 'new Form.Observer', 'type': 'constructor', 'path': '../dom/form/observer.html#new-constructor' },
'Abstract.EventObserver': { 'name': 'Abstract.EventObserver', 'type': 'class', 'path': '../dom/abstract/eventobserver.html' },
'Form.Element.EventObserver': { 'name': 'Form.Element.EventObserver', 'type': 'class', 'path': '../dom/form/element/eventobserver.html' },
'Form.Element.EventObserver': { 'name': 'Form.Element.EventObserver', 'type': 'class', 'path': '../dom/form/element/eventobserver.html' },
'Event': { 'name': 'Event', 'type': 'namespace', 'path': '../dom/event.html' },
'Event#isLeftClick': { 'name': 'Event#isLeftClick', 'type': 'instance method', 'path': '../dom/event.html#isleftclick-instance_method' },
'Event#isMiddleClick': { 'name': 'Event#isMiddleClick', 'type': 'instance method', 'path': '../dom/event.html#ismiddleclick-instance_method' },
'Event#isRightClick': { 'name': 'Event#isRightClick', 'type': 'instance method', 'path': '../dom/event.html#isrightclick-instance_method' },
'Event#element': { 'name': 'Event#element', 'type': 'instance method', 'path': '../dom/event.html#element-instance_method' },
'Event#findElement': { 'name': 'Event#findElement', 'type': 'instance method', 'path': '../dom/event.html#findelement-instance_method' },
'Event#pointer': { 'name': 'Event#pointer', 'type': 'instance method', 'path': '../dom/event.html#pointer-instance_method' },
'Event#pointerX': { 'name': 'Event#pointerX', 'type': 'instance method', 'path': '../dom/event.html#pointerx-instance_method' },
'Event#pointerY': { 'name': 'Event#pointerY', 'type': 'instance method', 'path': '../dom/event.html#pointery-instance_method' },
'Event#stop': { 'name': 'Event#stop', 'type': 'instance method', 'path': '../dom/event.html#stop-instance_method' },
'Event.observe': { 'name': 'Event.observe', 'type': 'class method', 'path': '../dom/event.html#observe-class_method' },
'Event.stopObserving': { 'name': 'Event.stopObserving', 'type': 'class method', 'path': '../dom/event.html#stopobserving-class_method' },
'Event.fire': { 'name': 'Event.fire', 'type': 'class method', 'path': '../dom/event.html#fire-class_method' },
'Element#fire': { 'name': 'Element#fire', 'type': 'instance method', 'path': '../dom/element.html#fire-instance_method' },
'Element#observe': { 'name': 'Element#observe', 'type': 'instance method', 'path': '../dom/element.html#observe-instance_method' },
'Element#stopObserving': { 'name': 'Element#stopObserving', 'type': 'instance method', 'path': '../dom/element.html#stopobserving-instance_method' },
'document': { 'name': 'document', 'type': 'namespace', 'path': '../dom/document.html' },
'document.fire': { 'name': 'document.fire', 'type': 'class method', 'path': '../dom/document.html#fire-class_method' },
'document.observe': { 'name': 'document.observe', 'type': 'class method', 'path': '../dom/document.html#observe-class_method' },
'document.stopObserving': { 'name': 'document.stopObserving', 'type': 'class method', 'path': '../dom/document.html#stopobserving-class_method' },
'document.loaded': { 'name': 'document.loaded', 'type': 'class property', 'path': '../dom/document.html#loaded-class_property' }
};